
package proyecto1;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;

/**
 *
 * @author GuillePC
 */
public class FrameInterfaz extends javax.swing.JFrame {
    DefaultListModel modelolista;
    hiloPC pc = new hiloPC();
    
    
    Lista P = new Lista(); // Se declara la lista enlazada de procesos
    int contpro =0; //Contador de procesos
    int contint =0; //Contador de procesos    
    
    
    
    public FrameInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        modelolista = new DefaultListModel();  
        jlistProcesos.setModel(modelolista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrearPro = new javax.swing.JButton();
        btnCrearInt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlistProcesos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbProceso = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        btnCrearPro.setText("Crear Proceso");
        btnCrearPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPro);
        btnCrearPro.setBounds(0, 370, 170, 25);

        btnCrearInt.setText("Crear Interrupcion");
        btnCrearInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearIntActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearInt);
        btnCrearInt.setBounds(0, 410, 170, 25);

        jScrollPane1.setViewportView(jlistProcesos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 330, 230, 230);

        jButton1.setText("Mostrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(37, 460, 120, 25);

        jLabel2.setText("Program Counter (PC)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 10, 200, 40);

        jLabel3.setText("Direccion de Memoria:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 126, 140, 20);

        txtDireccion.setEditable(false);
        txtDireccion.setText("direccion");
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(180, 120, 57, 30);

        jLabel4.setText("h");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(250, 130, 7, 16);

        jLabel5.setText("Proceso:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 160, 50, 16);

        lbProceso.setText("proceso");
        getContentPane().add(lbProceso);
        lbProceso.setBounds(180, 160, 70, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProActionPerformed
     
        // Processos se les asignara prioridad 2  
        // Instrucciones Prioridad 1 
        
        contpro++; // variable para contador de procesos
        String IdPro= "P"+ contpro; // Id del proceso 
        
       // Numero entero entre 5 y 15 Que sera la duracion del proceso
       // Primer numero es el tope del numero aleatorio
       // El segundo es el numero donde inicia 
       // Y el 1 para que no sea 0
       Random numRa = new Random();
       int Tiempo = numRa.nextInt(15-5+1) + 5;
       
        // Hora actual del sistema     
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss"); //Se filtra para el formato de la hora
        String Hora = hourdateFormat.format(date); //Asignar a una variable String
                      
        P.InsertarP(2,IdPro,Tiempo, Hora ); // Se agrega a la lista enlazada 
        // El primer valor es la prioridad, Segundo ID, Despues el tiempo que es aleatorio, Luego la hora
        modelolista.insertElementAt(IdPro,modelolista.size() ); //Se agrega a la lista
        if(!pc.espera) {pc.setProceso(P.getInicio()); pc.start();}
        jButton1ActionPerformed(evt);
        
        
    }//GEN-LAST:event_btnCrearProActionPerformed

    private void btnCrearIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearIntActionPerformed
       
        // Processos se les asignara prioridad 2  
        // Instrucciones Prioridad 1 
        contint++; // variable para contador de Interrupciones
        String IdInte= "I"+ contint; // Id de la interrupcion 
        
       // Numero entero entre 5 y 10 Que sera la duracion de la instruccion
       // Primer numero es el tope del numero aleatorio
       // El segundo es el numero donde inicia 
       // Y el 1 para que no sea 0
       Random numRa = new Random();
       int Tiempo = numRa.nextInt(15-5+1) + 5;
       
        // Hora actual del sistema     
        Date date = new Date();
        DateFormat hourdateFormat = new SimpleDateFormat("HH:mm:ss"); //Se filtra para el formato de la hora
        String Hora = hourdateFormat.format(date); // Asignar a una variable String
                      
        P.InsertarP(1,IdInte,Tiempo, Hora );
        // Se agrega a la lista enlazada 
        // El primer valor es la prioridad, Segundo ID, Despues el tiempo que es aleatorio, Luego la hora
        
        modelolista.add(0, IdInte); // Se agrega a la lista
        if(!pc.espera) {pc.setProceso(P.getInicio()); pc.start();}
        pc.newInt();

    }//GEN-LAST:event_btnCrearIntActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      P.Recorrer(0); 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameInterfaz().setVisible(true);
            }
        });
    }
    public class hiloPC extends Thread{
        hiloPC hilo;
        Nodo procesoInicial, proceso;
        boolean espera = false, interup = false;

        public void setProceso(Nodo proceso) {
            this.procesoInicial = proceso;
            espera = true;
        }
        public void newInt(){
            proceso = procesoInicial;
            interup = true;
        }

        public void run(){
           proceso = procesoInicial;
           while (true){
               if(espera){
                   if(interup){
                        if(proceso.getPrioridad() == 1){
                             if(!proceso.isTerminado()){
                                 proceso.setTiempoRe(proceso.getTiempoRe()-1);
                                 lbProceso.setText(proceso.getID()); 
                                 //txtDireccion.setText(proceso.getDireccion); direccion del proceso ??
                                 System.out.println("resta int: " + proceso.getID());
                                 if(proceso.getTiempoRe() == 0){
                                     System.out.println("Fin Int: " + proceso.getID());
                                     proceso.setTerminado(true);
                                     proceso = proceso.getsiguiente();
                                 }
                             }
                        }else{
                            interup=false;
                        }
                    }

                    if(!proceso.isTerminado()){
                         proceso.setTiempoRe(proceso.getTiempoRe()-1);
                         lbProceso.setText(proceso.getID()); 
                         //txtDireccion.setText(proceso.getDireccion); direccion del proceso ??
                         System.out.println("resta proc: " + proceso.getID());
                         if(proceso.getTiempoRe() == 0){
                             System.out.println("Fin proc: " + proceso.getID());
                             proceso.setTerminado(true);
                         }
                         proceso = proceso.getsiguiente();
                    }
               }
               try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(hiloPC.class.getName()).log(Level.SEVERE, null, ex);
                }
           }
        }   

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearInt;
    private javax.swing.JButton btnCrearPro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> jlistProcesos;
    private javax.swing.JLabel lbProceso;
    private javax.swing.JTextField txtDireccion;
    // End of variables declaration//GEN-END:variables
}
